/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PosPanels;

import pos.User;

/**
 *
 * @author Omer
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
       
        initComponents();
        user=new User();
    }
    public void setCurrentUser(User user){
        this.user=user;
    }
    public User getCurrentUser(){
        return user;
    }
    
    public void setUserDBPath(String userDBPath){
        this.userDBPath=userDBPath;
    }
    public String getUserDBPath(){
        return userDBPath;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POSSys V1.0");
        setBounds(new java.awt.Rectangle(50, 50, 1000, 600));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1050, 650));
        setName("POSSys V1.0"); // NOI18N
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


public void frameReset(){
    getContentPane().removeAll();
    getContentPane().repaint();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private User user;
    private String userDBPath;
}
